"""
retrieval/vector_store.py — Multi-Tenant Vector Store

Uses ChromaDB (in-memory) to provide per-region collection isolation.
Each region's documents live in a separate ChromaDB collection,
enforcing hard data boundaries at the storage layer.

Production equivalent on GCP:
  • Vertex AI Vector Search (formerly Matching Engine)
  • One index per region, or a single index with namespace/tenant_id
    metadata filtering (Vertex AI supports metadata-filtered ANN search).
  • Embeddings generated by Vertex AI text-embedding-004 (gecko).

Tenant Isolation Guarantee:
  • Regional collections are physically separate — a query to the
    "north" collection cannot return results from "east", even if
    the RBAC layer were somehow bypassed.
  • This is defence-in-depth: RBAC is the policy layer, the vector
    store is the enforcement layer.
"""

from __future__ import annotations

import os
import sys
from typing import Any

import chromadb

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import CHROMA_COLLECTION_PREFIX, TOP_K_RESULTS, REGIONS


class MultiTenantVectorStore:
    """
    Wrapper around ChromaDB that provides per-region tenant isolation.

    Each region maps to one ChromaDB collection named
    `bigburger_{region}`.  Queries are always scoped to one or more
    explicitly named collections — there is no "query all" method
    exposed to callers; cross-region fan-out is handled by the
    orchestrator agent.
    """

    def __init__(self) -> None:
        # In-memory client — no disk persistence needed for prototype.
        # Production: use chromadb.HttpClient pointing to a managed
        # ChromaDB instance, or swap the backend for Vertex AI Vector Search.
        self._client = chromadb.Client()
        self._collections: dict[str, chromadb.Collection] = {}
        self._ensure_all_collections()

    # ──────────────────────────────────────────────────────────────
    # Private helpers
    # ──────────────────────────────────────────────────────────────

    def _collection_name(self, region: str) -> str:
        return f"{CHROMA_COLLECTION_PREFIX}_{region}"

    def _ensure_all_collections(self) -> None:
        """Pre-create a collection for each known region."""
        for region in REGIONS:
            name = self._collection_name(region)
            self._collections[region] = self._client.get_or_create_collection(
                name=name,
                metadata={"hnsw:space": "cosine"},
            )

    def _get_collection(self, region: str) -> chromadb.Collection:
        if region not in self._collections:
            raise ValueError(
                f"Unknown region '{region}'. Valid regions: {REGIONS}"
            )
        return self._collections[region]

    # ──────────────────────────────────────────────────────────────
    # Write API
    # ──────────────────────────────────────────────────────────────

    def upsert_chunks(self, chunks: list[dict[str, Any]]) -> None:
        """
        Upsert a list of chunks into their respective regional collections.

        Uses upsert (not add) so re-ingestion of updated documents is
        idempotent — existing chunks are overwritten by chunk_id.
        """
        # Group by region first to batch writes per collection
        by_region: dict[str, list[dict[str, Any]]] = {}
        for chunk in chunks:
            by_region.setdefault(chunk["region"], []).append(chunk)

        for region, region_chunks in by_region.items():
            collection = self._get_collection(region)

            ids = [c["chunk_id"] for c in region_chunks]
            documents = [c["text"] for c in region_chunks]
            # ChromaDB metadata values must be str | int | float | bool
            metadatas = [
                {k: v for k, v in c.items() if k != "text"}
                for c in region_chunks
            ]

            collection.upsert(
                ids=ids,
                documents=documents,
                metadatas=metadatas,
            )

    def delete_document(self, region: str, doc_id: str) -> None:
        """
        Remove all chunks belonging to a document (e.g. when a Drive
        file is deleted or superseded by a new version).
        Uses ChromaDB's where-clause delete.
        """
        collection = self._get_collection(region)
        collection.delete(where={"doc_id": doc_id})

    # ──────────────────────────────────────────────────────────────
    # Read API
    # ──────────────────────────────────────────────────────────────

    def query_region(
        self,
        region: str,
        query_text: str,
        n_results: int = TOP_K_RESULTS,
    ) -> list[dict[str, Any]]:
        """
        Semantic similarity search within a single region's collection.

        Returns a list of result dicts, each containing:
          - text          (str)  chunk content
          - distance      (float) cosine distance (lower = more similar)
          - metadata      (dict) all chunk metadata fields
        """
        collection = self._get_collection(region)

        # Guard: don't request more results than documents exist
        count = collection.count()
        if count == 0:
            return []
        effective_n = min(n_results, count)

        raw = collection.query(
            query_texts=[query_text],
            n_results=effective_n,
        )

        results: list[dict[str, Any]] = []
        for i, doc_text in enumerate(raw["documents"][0]):
            results.append(
                {
                    "text": doc_text,
                    "distance": raw["distances"][0][i],
                    "metadata": raw["metadatas"][0][i],
                }
            )

        # Sort by ascending distance (closest / most relevant first)
        results.sort(key=lambda r: r["distance"])
        return results

    def collection_stats(self) -> dict[str, int]:
        """Return the chunk count per region — useful for diagnostics."""
        return {
            region: self._collections[region].count()
            for region in REGIONS
        }
